services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: nextjs_dashboard_db
      POSTGRES_USER: nextjs_dashboard_user
      POSTGRES_PASSWORD: nextjs_dashboard_password
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: